name: frontend
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.2
  share_plus: ^10.1.0
  fluttertoast: ^8.2.8
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  lottie: ^3.1.2
  infinite_scroll_pagination: ^4.0.0
  purchases_flutter: ^9.13.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  video_player: ^2.11.1
  flutter_dotenv: ^6.0.0
  emoji_picker_flutter: ^4.3.0
  loading_animation_widget: ^1.2.1
  flutter_image_compress: ^2.4.0
  easy_debounce: ^2.0.3
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/peace_bg_1.mp4
    - assets/peace_bg_2.mp4
    - assets/logo_v2.jpg
    - assets/intro1.mp4
    - assets/intro2.mp4
    - assets/intro3.mp4
    - assets/quotes/
    - .env
